server:
  port: 30000
  error:
    include-message: always


spring:
  application:
    name: coupon-gateway

  cloud:
    inetutils:
      preferred-networks: 172.16.60
    nacos:
      discovery:
        server-addr: 172.16.60.99:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        cluster-name: Cluster-A
        namespace: dev
        group: myGroup
        register-enabled: true
        naming-load-cache-at-start: false
        watch:
          enabled: true
        watch-delay: 30000
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: coupon-customer
          uri: lb://coupon-customer-serv
          predicates:
            - Path=/gateway/coupon-customer/**
          filters:
            - StripPrefix=1

        - id: test2
          uri: http://www.ifeng.com
          predicates:
            - Path=/**